### ISSUE TITLE
Takes up one CPU core on Firefox 33

### ISSUE THREAD

**Issue by lichtmetzger** [vovcacik/high-definition-video#12]
I just tested this add-on on Linux (HTML5, no Flash) and Firefox 33.

The add-on works fine, but it takes up one of my 4 cores and let's the browser lock-up for a little time every few seconds. Almost looks like something heavy is polling in the background.

That also affects a playing video, which makes the add-on a bit inconvenient.

**Comment by vovcacik** [comment]
Hi, I have been using it for some time in same environment like you and had no issue at all. Did it eventually worked for you or did you have to uninstall the addon?
