### ISSUE TITLE
Only 720p

### ISSUE THREAD

**Issue by GoodGuyNick** [vovcacik/high-definition-video#13]
Recently became change only to the 720p. Not 2k or 4k and not even 1080p, but only 720p. Tested in IceCat 31.2.0, FF 34 on my computer and in the virtual box. Sorry for English.

**Comment by vovcacik** [comment]
Hi, yes there was a change. Can you give me resolution of your monitor?

**Comment by GoodGuyNick** [comment]
1280x1024

**Comment by vovcacik** [comment]
In that case it is correct. Your optimum resolution for your monitor is 720p. Choosing quality higher than that is wasting your bandwidth.

**Comment by GoodGuyNick** [comment]
Age of dial-up is gone. And i want better image of the video. I guess soon i will be delete your extension because of the attitude of what you think is better for users when users want 1080p and higher.

**Comment by vovcacik** [comment]
Please note that your monitor can't display better 16:9 video than 720. If you play 1080 video or anything higher the video is downsized to 1280x720. Watching 4k video on your monitor won't produce better image quality and would be wasting of your resources (besides bandwidth also CPU).

The addon works within restrictions of your hardware, buy 4k monitor and it will happily select 4k for you.

**Comment by FlashFMA** [comment]
I'm sorry for my ignorance. I tested and you're right. But how about bitrate? It also remains the same?
