### ISSUE TITLE
Add dailymotion.com support.

### ISSUE THREAD

**Issue by vovcacik** [vovcacik/high-definition-video#5]
https://addons.mozilla.org/en-US/firefox/addon/high-definition-video/reviews/537489/

**Comment by tetsumaki** [comment]
Thanks for that.

**Comment by vovcacik** [comment]
@Tetsumaki unfortunately neither the [Player API](http://www.dailymotion.com/doc/api/player.html#api-reference) nor the [Javascript API](http://www.dailymotion.com/doc/api/sdk-javascript.html#dm-player-methods) expose any function to change playback quality.

One could change the playback quality of embedded Dailymotion videos using [query parameter](http://www.dailymotion.com/doc/api/player.html#parameters), but that would not work for Dailymotion.com itself.
