### ISSUE TITLE
Audio lost or muted.

### ISSUE THREAD

**Issue by vovcacik** [vovcacik/high-definition-video#6]
https://addons.mozilla.org/en-US/firefox/addon/high-definition-video/reviews/536928/

**Comment by ghost** [comment]
https://github.com/vovcacik/high-definition-video/issues/6

I know developers don't like to hear that but it happens sometimes, randomly even. This bug occur on all the YouTube links I visit like if the video try to load too fast.

------------------- Extensions --------------------
AdBlock Plus 2.4.1
Add to Search 2.2
Firebug 1.12.6
Flashblock 1.5.17
High Defition Video 1.0.2
Organize Search Engine 1.7
Stylish 1.4.1

--------------- Operating System --------------
Microsoft Windows 7 Professional (64bit)

I created a new Firefox Profile and it's still doing it. Also when I go in full screen as soon as the video start, the 720p or 1080p is not click-able for odd reasons. The YouTube video does not go in HD unless I exit full screen mode and pause the video. When I press start it goes back to HD but the sound is still not playing until I refresh the page. The HD issues just happened right now, could just be YouTube, I don't know if it's actually the extension. I tried to reproduce it and it's not working.

**Comment by vovcacik** [comment]
@Hyokkuda I gave it some time and I haven't had any problems. Actually I had issues with YouTube audio once, but that day YouTube were experiencing availability issue on its own.

As for the HD issue, this may be caused by preloading. The addon does its best to set high quality before playback starts, but in some cases the desired video quality is set after the playback started and therefore part of the video may be already preloaded in lower quality. If you would let the video play on the HD quality would eventually kick in (unless the video is really short and the whole video was preloaded in low quality).

**Comment by ghost** [comment]
Oh, the problem did not occurred in a long time now. I guess it was related to YouTube indeed. ^^

I edited my review and added a star to it.

**Comment by vovcacik** [comment]
Thats cool, thanks.
